export const actions = {
  GET_DATA: "GET_DATA",
  GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
  GET_DATA_ERROR: "GET_DATA_ERROR",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  HANDLE_CHANGE: "HANDLE_CHANGE",
  SAVE_USER: "SAVE_USER",
  SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
  SAVE_USER_ERROR: "SAVE_USER_ERROR",
  //edit
  ON_EDIT: "ON_EDIT",
  //delete
  OPEN_DELETE_MODAL: "OPEN_DELETE_MODAL",
  CLOSE_DELETE_MODAL: "CLOSE_DELETE_MODAL",
  HANDLE_FILTER_TEXT: "HANDLE_FILTER_TEXT",
   //pagination
   CHANGE_PAGE: "CHANGE_PAGE",
};
