export const actions = {
    GET_LIST: "GET_LIST",
    GET_LIST_SUCCESS: "GET_LIST_SUCCESS",
    GET_LIST_ERROR: "GET_LIST_ERROR",
    HANDLE_CHANGE: "HANDLE_CHANGE",
    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",
    SAVE_LIST: "SAVE_LIST",
    SAVE_LIST_SUCCESS: "SAVE_LIST_SUCCESS",
    SAVE_LIST_ERROR: "SAVE_LIST_ERROR",
    ON_EDIT: "ON_EDIT",
    OPEN_DELETE_MODAL: "OPEN_DELETE_MODAL",
    CLOSE_DELETE_MODAL: "CLOSE_DELETE_MODAL",
  };