export const initialState = {
  list: [],
  loadingGetList: true,
  errorTextGetList: "",
  showModal: false,
  body: {
    petId: 0,
    vetId: 0,
    type: "",
    price: 0,
    dateApplication: "",
    nextApplication: "",
    weight: 0,
  },
  loadingSaveList: false,
  errorTextSaveList: "",
  reload: false,
  isEdit: false,
  showDeleteModal: false,
  filterText: "",
};
