export const actions = {
  GET_USER_INFO: "GET_USER_INFO",
  GET_USER_INFO_SUCCESS: "GET_USER_INFO_SUCCESS",
  GET_USER_INFO_ERROR: "GET_USER_INFO_ERROR",
  SAVE_PET_INFO: "SAVE_PET_INFO",
  SAVE_PET_INFO_SUCCESS: "SAVE_PET_INFO_SUCCESS",
  SAVE_PET_INFO_ERROR: "SAVE_PET_INFO_ERROR",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  HANDLE_INPUT_CHANGE: "HANDLE_INPUT_CHANGE",
  CHANGE_SCREEN_POSITION: "CHANGE_SCREEN_POSITION",
  SELECT_PET: "SELECT_PET",
};
