export const initialState = {
  showModal: false,
  isLoadingUserInfo: false,
  errorTextUserInfo: "",
  isLoadingSavePet: false,
  errorTextSavePet: "",
  reload: false,
  screenPosition: 0,
  user: {
    id: 0,
    name: "",
    lastName: "",
    phone: "",
    address: "",
    city: "",
    state: "",
    statusDelete: false,
    pets: [],
  },
  pet: {
    name: "",
    specie: "",
    race: "",
    sex: "",
    color: "",
    birthDate: "",
    allergies: "",
    weight: 0,
    photo: "",
    isDigitAge: false,
  },
  petSelected: null,
  isEdit: false,
  initialLoad: false,
};
