export const actions = {
  GET_LIST: "GET_LIST",
  GET_LIST_SUCCESS: "GET_LIST_SUCCESS",
  GET_LIST_ERROR: "GET_LIST_ERROR",
  HANDLE_FILTER_TEXT: "HANDLE_FILTER_TEXT",
  CHANGE_PAGE: "CHANGE_PAGE",
  CHANGE_MONTH: "CHANGE_MONTH",
  CHANGE_DAY: "CHANGE_DAY",
};
