export const initialState = {
  list: [],
  loadingGetList: true,
  errorTextGetList: "",
  showModal: false,
  body: {
    petId: 0,
    vetId: 0,
    date: "",
    treatment: "",
    description: "",
    price: "",
  },
  loadingSaveList: false,
  errorTextSaveList: "",
  reload: false,
  isEdit: false,
  showDeleteModal: false,
  filterText: "",
  page: 1,
  pageSize: 5,
};
