export const actions = {
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  SAVE_USER: "SAVE_USER",
  SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
  SAVE_USER_ERROR: "SAVE_USER_ERROR",
  HANDLE_CHANGE: "HANDLE_CHANGE",
  EDIT_USER: "EDIT_USER",
};
