export const actions = {
  GET_LIST: "GET_LIST",
  GET_LIST_SUCCESSS: "GET_LIST_SUCCESS",
  GET_LIST_ERROR: "GET_LIST_ERROR",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  SAVE_USER: "SAVE_USER",
  SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
  SAVE_USER_ERROR: "SAVE_USER_ERROR",
  HANDLE_CHANGE: "HANDLE_CHANGE",
  HANDLE_FILTER_TEXT: "HANDLE_FILTER_TEXT",
};
